-- Create interview recordings table
CREATE TABLE IF NOT EXISTS `tblinterviewrecordings` (
  `RECORDING_ID` int(11) NOT NULL AUTO_INCREMENT,
  `REGISTRATIONID` varchar(50) NOT NULL,
  `QUESTION_NUMBER` int(11) NOT NULL DEFAULT 0,
  `FILE_PATH` varchar(500) NOT NULL,
  `DURATION` decimal(10,3) NOT NULL DEFAULT 0.000,
  `RECORDED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CONVERSATION_TURN` int(11) NOT NULL DEFAULT 0,
  `QUESTION_TYPE` varchar(50) NOT NULL DEFAULT 'initial_answer',
  `TRANSCRIPT` text,
  PRIMARY KEY (`RECORDING_ID`),
  KEY `REGISTRATIONID` (`REGISTRATIONID`),
  KEY `RECORDED_AT` (`RECORDED_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Create interview invitations table if it doesn't exist
CREATE TABLE IF NOT EXISTS `tblinterviewinvitations` (
  `INVITATION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `REGISTRATIONID` varchar(50) NOT NULL,
  `JOBID` varchar(50) NOT NULL,
  `TOKEN` varchar(255) NOT NULL,
  `EXPIRY_DATE` timestamp NOT NULL,
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `STATUS` enum('pending','completed','expired') NOT NULL DEFAULT 'pending',
  PRIMARY KEY (`INVITATION_ID`),
  UNIQUE KEY `TOKEN` (`TOKEN`),
  KEY `REGISTRATIONID` (`REGISTRATIONID`),
  KEY `EXPIRY_DATE` (`EXPIRY_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; 