-- Setup Interview Columns
-- Adds required columns to tbljobregistration table for interview results functionality

USE erisdb;

-- Add INTERVIEW_RESULTS column
ALTER TABLE tbljobregistration ADD COLUMN IF NOT EXISTS INTERVIEW_RESULTS TEXT NULL;

-- Add INTERVIEW_STATUS column
ALTER TABLE tbljobregistration ADD COLUMN IF NOT EXISTS INTERVIEW_STATUS VARCHAR(20) DEFAULT NULL;

-- Add INTERVIEW_COMPLETED_AT column
ALTER TABLE tbljobregistration ADD COLUMN IF NOT EXISTS INTERVIEW_COMPLETED_AT DATETIME NULL;

-- Add ADMIN_GRADE column
ALTER TABLE tbljobregistration ADD COLUMN IF NOT EXISTS ADMIN_GRADE TEXT NULL;

-- Add GRADED_AT column
ALTER TABLE tbljobregistration ADD COLUMN IF NOT EXISTS GRADED_AT DATETIME NULL;

-- Add EMAIL_SENT column
ALTER TABLE tbljobregistration ADD COLUMN IF NOT EXISTS EMAIL_SENT TEXT NULL;

-- Add EMAIL_SENT_AT column
ALTER TABLE tbljobregistration ADD COLUMN IF NOT EXISTS EMAIL_SENT_AT DATETIME NULL;

-- Verify columns were added
SELECT COLUMN_NAME, DATA_TYPE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA = 'erisdb' 
AND TABLE_NAME = 'tbljobregistration' 
AND COLUMN_NAME IN ('INTERVIEW_RESULTS', 'INTERVIEW_STATUS', 'INTERVIEW_COMPLETED_AT', 'ADMIN_GRADE', 'GRADED_AT', 'EMAIL_SENT', 'EMAIL_SENT_AT')
ORDER BY COLUMN_NAME;